### ISSUE TITLE
Link color wrong

### ISSUE THREAD

**Issue by garyyo** [drakeapps/synccit#9]
when using a custom style with stylish the link is colored to some bizarre default color instead of my own custom styled colors. its barely readable to me.
![image](https://user-images.githubusercontent.com/392790/29444576-ba0bfc86-83ae-11e7-9a72-3fd287966f23.png)

**Comment by drakeapps** [comment]
The extension has been updated to just dim the link instead of change the link color. As far as I know, there isn't a way to read the visited link color to be able to adjust the colors
